version: '3.8'
services:
  db:
    image: postgres
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_DB=patientDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - db-volume:/var/lib/postgresql@14/data
  api:
    image: ${DOCKER_REGISTRY-}patient-test-task
    build: 
        dockerfile: Dockerfile
    depends_on: [db]
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80 
    ports:
       - "3500:80"
volumes:
  db-volume:

